baseURL = '127.0.0.1'
languageCode = 'en-us'
title = 'idk what to name this'
theme = "smigle"

[params]
    author = "Prakhar Gupta"
    subtitle = "confused undergrad studying ece"
    
    [[params.social]]
        name = "GitHub"
        url = "https://github.com/screamingpigeon"
    [[params.social]]
        name = "LinkedIn"
        url = "https://linkedin.com/in/prakg"

        

[menu]
    [[menu.main]] 
        name = "Home"
        pageRef = "/"
        weight = 1
    [[menu.main]] 
        name = "About Me"
        pageRef = "/about"
        weight = 2
    [[menu.main]] 
        name = "Research"
        pageRef = "/research/"
        weight = 3
    [[menu.main]] 
        name = "Projects"
        pageRef = "/projects/"
        weight = 4
    [[menu.main]] 
        name = "Blog"
        pageRef = "/blog/"
        weight = 5

